kind: Task
metadata:
  name: "Get mesh namespaces"
  category: "Resource Inspection"
  difficulty: easy
steps:
  setup:
      inline: |-
        #!/usr/bin/env bash
  verify:
    contains: "namespaces in your mesh"
  cleanup:
    inline: |-
      #!/usr/bin/env bash          
  prompt:
    inline: Check namespaces in my mesh.