name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.25
  UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}

permissions:
  contents: write
  id-token: write  # Required for npmjs OIDC
  discussions: write

jobs:
  release:
    name: Release
    if: github.repository == 'containers/kubernetes-mcp-server'
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: make build-all-platforms
      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          files: |
            LICENSE
            kubernetes-mcp-server-*
      # Ensure npm 11.5.1 or later is installed (required for https://docs.npmjs.com/trusted-publishers)
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Publish npm
        run:
          make npm-publish
  python:
    name: Release Python
    if: github.repository == 'containers/kubernetes-mcp-server'
    # Python logic requires the tag/release version to be available from GitHub
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - name: Publish Python
        run:
          make python-publish
